package com.example.bankomat.entity.enums;

public enum PermissionEnum {

    USER_CRUD,READ_USER,READ_ONE_USER,ADD_USER,EDIT_USER,DELETE_USER,
    BANK_CRUD,READ_BANK,READ_ONE_BANK,ADD_BANK,EDIT_BANK,DELETE_BANK,
    CARD_CRUD,CARD_READ,READ_ONE_CARD,ADD_CARD,EDIT_CARD,DELETE_CARD,
    BANKOMAT_CRUD,READ_BANKOMAT,READ_ONE_BANKOMAT,ADD_BANKOMAT,EDIT_BANKOMAT,DELETE_BANKOMAT,
    WORK_WITH_ATM;
}
